version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@2.0.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  frontend:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-frontend
      - run:
          name: Building Frontend Project
          command: npm run build
      - aws-cli/install
      - run:
          name: Run Testing Frontend
          command: npm run test
      - run:
          name: Deploying Frontend Project
          command: aws s3 cp --recursive --acl public-read ./www s3://ezzhassan-udagram/
  server:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-api
      - run:
          name: Building Server Project
          command: |-
            npm run build
      - aws-cli/install
      - run:
          name: Deploy Server
          command: |-
            aws s3 cp ./www/Archive.zip $S3_BUCKET_SERVER
            aws elasticbeanstalk create-application-version --application-name $EB_APP --version-label <<pipeline.git.revision>> --source-bundle S3Bucket="$EB_BUCKET",S3Key="Archive.zip"
            aws elasticbeanstalk update-environment --application-name $EB_APP --environment-name $EB_ENV --version-label <<pipeline.git.revision>>
workflows:
  build_and_deploy:
    jobs:
      - frontend
      - server
