version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@2.0.0


  jobs:
      deploy:
        docker:
          img: cimg/node:14.17
        steps:
        # Check for latest change to the Repo
          -checkout
          - restore_cache:
          # Check to see if any dependencies is already installed
            keys:
              - v1-dependencies-{{checksum "package.json"}}
              - v1-dependencies-
          # If no package is installed then Install and Cache them
          - run:
              name: Install NPM dependencies
              command: npm install
          - save_cache:
              paths:
                node_modules
              -key: v1-dependencies-{{checksum "package.json"}}
          - run:
              name: Building Project
              command: npm run build
            - aws-cli/install
          - run:
              name: Run Testing
              command: npm run test
          - run:
              name: Deploy to AWS s3
              command: aws s3 cp --recursive --acl public-read ./www s3://ezzhassan-udagram/


  workflow: build_deploy
