version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@2.0.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  frontend:
    working_directory: ~/app/udagram/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram/udagram-frontend
      - run:
          name: Build Frontend
          command: npm run build
      - aws-cli/install
      - run:
          name: Deploy Frontend
          command: aws s3 cp --recursive --acl public-read ./www s3://ezzhassan-udagram/
  server:
    machine:
      image: ubuntu-2004:202010
    working_directory: ~/app/udagram/udagram-api
    executor: node/default
    steps:
      - checkout:
      - run:
        name: Install Linux needed packages
        command: |-
          sudo apt-get update
          sudo apt install python3-pip
          sudo pip3 install awsebcli --upgrade
      - node/install-packages:
          app-dir: ~/app/udagram/udagram-api
      - run:
        name: Install Linux needed packages
        command: |-
          cd www
          eb init --region us-east-1 --platform node.js udagram
          eb use udagram-api-dev
          eb deploy
      - run:
          name: Build and Archive Server
          command: |-
            npm run build
      - aws-cli/install
      - run:
          name: Deploy Server
          command: |-
            cd www
            eb init --region us-east-1 --platform node.js udagram
            eb use udagram-api-dev
            eb deploy

workflows:
  build_and_deploy:
    jobs:
      - frontend
      - server
