version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@2.0.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  frontend:
    working_directory: ~/app/udagram/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram/udagram-frontend
      - run:
          name: Build Frontend
          command: npm run build
      - aws-cli/install
      - run:
          name: Deploy Frontend
          command: aws s3 cp --recursive --acl public-read ./www s3://ezzhassan-udagram/
  server:
    working_directory: ~/app/udagram/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram/udagram-api
      - run:
          name: Build and Archive Server
          command: |-
            npm run build
      - aws-cli/install
      - run:
          name: Deploy Server
          command: |-
            aws s3 cp ./www/Archive.zip ezzhassan-udagram
            aws elasticbeanstalk create-application-version --application-name udagram --version-label <<pipeline.git.revision>> --source-bundle S3Bucket="ezzhassan-udagram",S3Key="Archive.zip"
            aws elasticbeanstalk update-environment --application-name udagram --environment-name udagram-api-dev --version-label <<pipeline.git.revision>>

workflows:
  build_and_deploy:
    jobs:
      - frontend
      - server
